var express = require("express");
var router = express.Router();
var auth = require("../middlewares/user_auth");

var body_measurement = require("./user/measurement");
var nutrition_preference = require("./user/nutrition_preferences");
var profile = require("./user/profile");
var equipment = require("./user/equipment");
var exercise_preference = require("./user/exercise_preference");
var user_progress_photos = require("./user/user_progress_photos");
var user_posts = require("./user/user_posts");
var gallery = require("./user/gallery");
var exercise_types = require("./user/exercise_type");
var exercise = require("./user/exercise");
var bodypart = require("./user/bodyparts");
var shopping_cart = require("./user/shopping_cart");
var friends = require("./user/friends");
var comment = require("./user/comment");
var like = require("./user/like");
var recipe = require("./user/user_recipe");
var nutrition = require("./user/nutrition");
var test_exercises = require("./user/test_exercises");
var user_workout = require("./user/user_workout");
var timeline = require("./user/timeline");

router.use("/measurement", auth, body_measurement);
router.use("/nutrition_preference", auth, nutrition_preference);
router.use("/profile", auth, profile);
router.use("/equipment", auth, equipment);
router.use("/exercise_preference", auth, exercise_preference);
router.use("/progress_photo", auth, user_progress_photos);
router.use("/user_post", auth, user_posts);
router.use("/gallery", auth, gallery);
router.use("/exercise_type", auth, exercise_types);
router.use("/exercise", auth, exercise);
router.use("/bodypart", auth, bodypart);
router.use("/friend", auth, friends);
router.use("/comment", auth, comment);
router.use("/like", auth, like);
router.use("/recipe", auth, recipe);
router.use("/nutrition", auth, nutrition);
router.use("/test_exercise", auth, test_exercises);
router.use("/shopping_cart", auth, shopping_cart);
router.use("/workout", auth, user_workout);
router.use("/timeline", auth, timeline);

module.exports = router;
